<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the sessions table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-12 15:04:43
 */
class SessionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('sessions')->truncate();
        
        // Insert data in chunks
        DB::table('registration')->insert([
            [
                'id' => 'Qg79YOZDJ0lsoaDwcVHU4a2TCbDmczeHhxXlKmA2',
                'user_id' => null,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.118.1 Chrome/142.0.7444.265 Electron/39.8.8 Safari/537.36',
                'payload' => 'eyJfdG9rZW4iOiJYUEViS083RzQwOHBiajNPbFRiYXBxSEd3M0Uxd0NNejhvWFJrbW1IIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEyNy4wLjAuMTo4MDAwIiwicm91dGUiOm51bGx9LCJfZmxhc2giOnsib2xkIjpbXSwibmV3IjpbXX19',
                'last_activity' => 1778595325,
            ],
            [
                'id' => 'nZ0EXbHI2ElGUR8n72MbFSPsbaWkjDhJa9hRlpnC',
                'user_id' => null,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.118.1 Chrome/142.0.7444.265 Electron/39.8.8 Safari/537.36',
                'payload' => 'eyJfdG9rZW4iOiJIeFF6Sko3bTE1SzROUTRlM2hsOFAyQnJPelRFVm5GMkFJTG9QSlAzIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEyNy4wLjAuMTo4MDAwXC90cmFuc2NyaXB0XC9EQ00yMjExNzc/dGVtcGxhdGU9d29yZCIsInJvdXRlIjoidHJhbnNjcmlwdC5nZW5lcmF0ZSJ9LCJfZmxhc2giOnsib2xkIjpbXSwibmV3IjpbXX19',
                'last_activity' => 1778574488,
            ],
            [
                'id' => 'djm8vkkr6esG5XK9aBYvhHkYz08BNxg8ml2LJ2Xc',
                'user_id' => null,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
                'payload' => 'eyJfdG9rZW4iOiJnd1FFZHlPRnJOZ3Zxd2VKbXIwQjZERnJJVUdETFZFeWF6OWJxb3pyIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEyNy4wLjAuMTo4MDAwXC90cmFuc2NyaXB0XC9EQ00yMjExNTQ/dGVtcGxhdGU9d29yZCIsInJvdXRlIjoidHJhbnNjcmlwdC5nZW5lcmF0ZSJ9LCJfZmxhc2giOnsib2xkIjpbXSwibmV3IjpbXX19',
                'last_activity' => 1778057406,
            ],
            [
                'id' => 'gXjSyDlJ0Hts9Sv7r73o2so2uJLUp2jysIZkFFaA',
                'user_id' => null,
                'ip_address' => '127.0.0.1',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
                'payload' => 'eyJfdG9rZW4iOiJCMjA3UDl4Z3Z6WnZTR0poTExDRGpMdHNUZjVkcGczeFlHV1BlVXRPIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cLzEyNy4wLjAuMTo4MDAwXC90cmFuc2NyaXB0XC9EQ00yMjExMTI/dGVtcGxhdGU9d29yZCIsInJvdXRlIjoidHJhbnNjcmlwdC5nZW5lcmF0ZSJ9LCJfZmxhc2giOnsib2xkIjpbXSwibmV3IjpbXX19',
                'last_activity' => 1778595425,
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}