<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration class for creating the registration table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-12 15:02:44
 */


return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('registration', function (Blueprint $table) {
            $table->id('id');
            $table->string('studentid', 30);
            $table->integer('semesterid');
            $table->integer('courseid');
            $table->string('campusid', 100)->nullable();
            $table->string('grade', 11)->nullable();
            $table->string('assign1', 9)->nullable();
            $table->integer('midterm')->nullable();
            $table->float('points')->nullable();
            $table->string('res', 100)->nullable();
            $table->integer('adviserapp')->nullable();
            $table->integer('fnceapp')->nullable();
            $table->integer('credits')->nullable();


        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('registration');
    }
};