<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration class for creating the people table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-05-12 15:02:44
 */


return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('people', function (Blueprint $table) {
            $table->id('id');
            $table->string('username', 255);
            $table->string('fullname', 255);
            $table->string('password', 255);
            $table->string('dob', 15)->nullable();
            $table->string('sex', 10)->nullable();
            $table->integer('majorid');
            $table->integer('campusid')->nullable();
            $table->integer('typeid')->nullable();
            $table->string('cell', 255)->nullable();
            $table->string('address', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('nationalityid', 255)->nullable();
            $table->string('religionid', 155)->nullable();
            $table->year('startyear')->nullable();
            $table->string('sponsor', 255)->nullable();
            $table->string('role', 128)->nullable();
            $table->string('image_path', 100)->nullable();
            $table->string('marital', 10)->nullable();
            $table->string('spcell', 15)->nullable();
            $table->string('spemail', 100)->nullable();

            $table->unique('username');

        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('people');
    }
};